config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  scope '/espacio' do
    get '/', to: 'main#espacio', as: 'espacio'
    get '/products/(:category_type)/(:category_id)/(:category_name)', to: 'main#products_by_category', as: 'products_by_category'
    get '/set_background/(:category_type)/(:product_sku)', to: 'main#set_background', as: 'set_background'
    get '/carrito_add/(:product_sku)', to: 'main#carrito_add', as: 'carrito_add'
    post '/carrito_send', to: 'main#carrito_send', as: 'carito_send'
    post '/set_tienda', to: 'main#set_tienda', as: 'set_tienda'
    post '/impresion_send', to: 'main#impresion_send', as: 'impresion_send'
    post '/cubicador_send', to: 'main#cubicador_send', as: 'cubicador_send'
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
	around_filter :protect_request, only: [:products_by_category, :carrito_add, :set_background, :carrito_send, :set_tienda]
	
	CATEGORIES_TYPES = {
		muro: 'muro',
		piso: 'piso'
	}
	PDF_TEMP_FILE = Rails.root.join('tmp', 'prueba.pdf')

	def index
		render action: :index
	end

	def espacio
		carrito = Carrito.new
		# carrito.items << ProductPair.new(piso: Product.new(sku: "1"), muro: Product.new(sku: "2"))
		# carrito.items << ProductPair.new(piso: Product.new(sku: "3"), muro: Product.new(sku: "4"))
		render action: :espacio, locals: {categories_types: CATEGORIES_TYPES, carrito: carrito, categories: Category.all}
	end

	def products_by_category
		if params[:category_type].present?
			if params[:category_id].present?
				res = API.getProductsByCategory(categoria_id: params[:category_id], category_type: params[:category_type], category_name: params[:category_name])

				# category_obj = Category.select(:nombre).find_by(sodimac_id: params[:category_id], tipo: params[:category_type])

				if !res.nil?
					html_item_arr = []
					res[:products].each_with_index do |item, index|
						html_item_arr << render_to_string(partial: 'carousel_items', formats: [:html], layout: false, locals: {item: item, type: Product.new, index: index, category: res[:category_obj]})
					end

					render json: {
						carousel_items: html_item_arr,
						carousel_type: params[:category_type],
						source: res[:source],
						last_updated_at: res[:category_obj].last_api_used
					}
				else
					# Hubo un error al obtener los productos de la categoria.
					render json: {msg: "Hubo un error en obtener los productos de la categoria '#{params[:category_id]}'"}, status: :unprocessable_entity	
				end		
			else
				# No hay id de categoria.
				render json: {msg: "El servidor no recibió el id de la categoria."}, status: :unprocessable_entity
			end
		else
			# No hay tipo de categoria.
			render json: {msg: "El servidor no recibió el tipo de la categoria."}, status: :unprocessable_entity
		end
	end

	def carrito_add
		if !params[:product].nil?
			product_obj = Product.getProductBySku(params[:product][:sku], {cantidad: params[:product][:cantidad]})

			if !product_obj.nil?
				carrito_obj = Carrito.new
				carrito_obj.items << product_obj
				carrito_obj.calculateTotal

				render json: {
					carrito_item: render_to_string(partial: 'carrito_form', formats: [:html], layout: false, locals: {carrito: carrito_obj}),
					item_sku: product_obj.sku,
					precio_total_item: carrito_obj.total
				}
			else
				render json: {msg: "Hubo problemas en encontrar el producto en la BD."}, status: :unprocessable_entity
			end
		else
			render json: {msg: "Hubo problemas en enviar los datos del producto al servidor"}, status: :unprocessable_entity
		end
	end

	def carrito_send
		if !params[:items].nil?
			if params[:email].present?
				# Verificar el formato del email ingresado.
				if params[:email] =~ /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
					pdf_options = {pisos: [], muros: []}

					# Recorrer los pisos y muros para obtener su ficha y asi poder generar el PDF.
					params[:items].each do |item|
						product_obj = API.getFichaProductoBySku(item[1][:sku], item[1][:tipo])
						if !product_obj.nil?
							if product_obj.tipo == "piso"
								pdf_options[:pisos] << product_obj
							elsif product_obj.tipo == "muro"
								pdf_options[:muros] << product_obj
							end
						end
					end

					# Crear PDF. 
					pdf = Pdf.new(pdf_options)

					# Guardar el archivo PDF en local.
			    	pdf.render_file(PDF_TEMP_FILE.to_s)

					# Enviar el email con el PDF.
					PdfMailer.pdf_email(params[:email], PDF_TEMP_FILE.to_s).deliver_later

					render json: {msg: "Email enviado a #{params[:email]} con el pdf generado exitosamente.", home_url: espacio_path, archivo: PDF_TEMP_FILE.to_s}
					
				else
					render json: {msg: "El formato del email ingresado no es válido."}, status: :unprocessable_entity
				end
			else
				render json: {msg: "No hay email."}, status: :unprocessable_entity
			end
		else
			render json: {msg: "El carrito de compras esta vacio."}, status: :unprocessable_entity
		end
	end

	def set_background
		if params[:category_type].present?
			if params[:product_sku].present?
				product_obj = API.getFichaProductoBySku(params[:product_sku], params[:category_type])

				# Verificar que el objeto tenga la imagen a setear.
				if product_obj.img_url.present?
					# Correr el comando para setear la imagen.
					res = system("wallpaper #{product_obj.img_url}")
					
					if res
						render json: {msg: "Imagen de producto seteada exitosamente."}
					else
						render json: {msg: "Hubo un problema en setear la imagen."}, status: :unprocessable_entity
					end
				end
			else
				render json: {msg: "No llego el sku del producto al servidor."}, status: :unprocessable_entity
			end
		else
			render json: {msg: "No llego el tipo de producto al servidor."}, status: :unprocessable_entity
		end
	end

	def set_tienda
		tienda_obj = Tienda.find_by(numero: params[:config][:tienda_id])

		if !tienda_obj.nil?
			config_obj = Config.getTiendaConfig
			config_obj.tienda_id = tienda_obj.id

			if config_obj.save
				render json: {msg: "Tienda ingresada exitosamente", tienda_config: Config.checkTiendaConfig}
			else
				render json: {msg: "Hubo un problema en guardar la tienda seleccionada."}, status: :unprocessable_entity
			end

		else
			render json: {msg: "La tienda ingresada no existe en la BD."}, status: :unprocessable_entity
		end
	end

	def impresion_send
		if !params[:items].nil?
			if params[:nombre].present?
				# Verificar el formato del email ingresado.
				if params[:email] =~ /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
					# Veriicar el rut ingresado.
					if RUT::validar(params[:rut])
						res = API.sendToImpresion(params[:items], {nombre: params[:nombre], email: params[:email], rut: params[:rut]})

						if !res.nil?
							# OK.
							render json: {msg: "Solicitud de impresion enviada exitosamente.", ticket: res}
						else
							# Hubo un error al mandar el request de impresion.
							render json: {msg: "Hubo un problema en mandar la solicitud de impresion."}, status: :unprocessable_entity
						end
					else
						render json: {msg: "Rut invalido."}, status: :unprocessable_entity
					end
				else
					render json: {msg: "Email invalido."}, status: :unprocessable_entity
				end
			else
				render json: {msg: "No hay nombre."}, status: :unprocessable_entity
			end
		else
			render json: {msg: "El carrito de compras esta vacio."}, status: :unprocessable_entity
		end
	end

	def cubicador_send
		res = API.sendToCubicador(params[:cubicador])
		if !res.nil?
			# OK.
			render json: {msg: "Solicitud del cubicador realizada exitosamente.", cantidad: res}
		else
			render json: {msg: "Hubo un problema con el cubicador."}, status: :unprocessable_entity
		end
	end

	def protect_request
		begin
			yield
		rescue StandardError => e
			puts e
			puts e.backtrace
			render json: {msg: "Ha ocurrido un error con el request."}, status: :unprocessable_entity 
		end
	end	

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_carousel_items.html.erb
<%= fields_for(type) do |f| %>
  <!--<div class="col s4 m4">-->
  <a class="col s4 m4" >
    <div class="card medium hoverable">
      <!--<div class="card-image">
        <img class="img-responsive" src="<%= item.img_url %>">
      </div>-->
      <a class="card-image scale-transition set_background" data-img_url="<%= item.img_url %>">
        <img class="img-responsive" src="<%= item.img_url %>">
      </a>
      <li class="divider"></li>
      <div class="card-content" style="padding-top:10px; ">
        <p>Descripcion: <%= item.descripcion %></p>
        <p>Rendimiento por caja: <%= item.rend_caja %></p>
        <p>Precio: $<%= number_with_delimiter(item.precio, :delimiter => ',') %></p>
        <p>SKU: <%= item.sku %></p>
        <div style="position:absolute; bottom:15px; left:15px; right:15px;">
          <div style="float:left; width:33%;padding-top:20px;">
          
          <!--   <button class="btn-floating btn-small scale-transition set_background" data-img_url="<%= item.img_url %>">
          <i class="material-icons">visibility</i>
        </button>--><!-- Boton de visibilidad-->
          
        </div>
          <div style="float:left; width:33%; text-align:center;padding-top:20px;">
            <a href="<%= carrito_add_path(item.sku) %>" class="btn-floating btn-small scale-transition shopping_cart">
              <i class="material-icons">shopping_basket</i>
            </a>
          </div>
          <% if item.tipo == "piso" %>
            <div style="float:left; width:33%; text-align:right;padding-top:20px;">
              <button class="btn-floating btn-small scale-transition 3d_rotation rotate_background" data-img_url="<%= item.img_url %>">
                <i class="material-icons">select_all</i><!--cambie este icono -->
              </button>
            </div>
          <% end -%>
        </div>
        <%= f.hidden_field(:sku, value: item.sku) %>
        <%= f.hidden_field(:precio, value: item.precio) %>
        <%= f.hidden_field(:tipo, value: item.tipo) %>
        <%= f.hidden_field(:cantidad, value: item.cantidad) %>
        <%= f.hidden_field(:categoria, value: category.nombre.downcase) %>
        <%= f.hidden_field(:superficie, value: item.superficie) %>
      </div>
    </div>
  <!--</div>-->
  </a>
<% end -%>

app/views/main/_carrito_form.html.erb
<% carrito.items.each do |item| %>
  <%= fields_for("items[]", item) do |ff| %>
    <li class="valign-wrapper" data-product-sku="<%= item.sku %>" data-product-price="<%= item.precio %>">
      <%= ff.hidden_field(:sku, value: item.sku) %>
      <%= ff.hidden_field(:tipo, value: item.tipo) %>
      <div class="col s2 offset-s1">
        <button type="button" class="btn-floating btn-small btn-flat cantidad-rem-btn <% if item.cantidad == 1 %> disabled <% end %>"><i class="material-icons">remove</i></button>
        <%= ff.number_field(:cantidad, value: item.cantidad, min: 1, class: 'cantidad-item center-align') %>
        <button type="button" class="btn-floating btn-small btn-flat cantidad-add-btn"><i class="material-icons">add</i></button>
      </div>
      <div class="col s2 offset-s1">
      	<label class="input-field right-align"><%= item.tipo.to_s.titleize %> sku: <%= item.sku %> | Precio: $ <%= number_with_delimiter(item.precio, :delimiter => ',') %></label >
			</div>
    </li>
  <% end -%>
<% end -%>

app/views/main/espacio.html.erb
<%= content_for :css do %>
  <%= stylesheet_link_tag 'new_windows', media: 'all', 'data-turbolinks-track' => true, 'data-only_window' => true %>
<% end -%>

<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <%= form_for(carrito, url: carito_send_path, html: {id: 'carrito_form', format: :json}) do |f| %>
      <div id="carrito_container" class="col s12 row">
        
      </div>
      <li class="divider"></li>
      <li data-total="<%= carrito.total %>" id="carrito-precio-total">
        <span>Total: $<%= carrito.total %></span>
      </li>
      <li>
        <a class="waves-light btn" href="#modal1">Enviar</a>
      </li>
      <li>
        <a class="waves-light btn" href="#modal4"">Imprimir</a>
      </li>
  <% end -%>
</ul>

<div id="modal1" class="modal">
  <div class="modal-content">
    <button class="close" id="close-modal1"><i class="material-icons">close</i></button>
    <h4>Ingresa tu correo </h4>
    <div class="input-field col s12">
      <input type="email", class="validate vk1", placeholder="Email", id="email_modal">
    </div>
  </div>
  <div class="modal-footer">
    <input type="button", id="buttonModal1", class="waves-light btn modal-trigger", value="Enviar">
  </div>
</div>
<!-- MODAL el trigger es el boton enviar -->
<div id="modal2" class="modal">
  <div class="modal-content">
    <button class="close" id="close-modal2"><i class="material-icons">close</i></button>
    <h4>Su mensaje fue enviado</h4>
    <h6>Gracias por preferirnos</h6>
  </div>
  <div class="modal-footer">
    <input type="button", id="buttonModal2", class="modal-action modal-close  btn-flat", value="Cerrar">
  </div>
</div><!--modal mensaje final el trigger es el boton enviar del modal 1-->

<!-- MODAL el trigger es el boton enviar -->
<div id="imp_success_modal" class="modal">
  <div class="modal-content">
    <button class="close" id="close-imp-success"><i class="material-icons">close</i></button>
    <h4>Cotización enviada a impresión exitosamente.</h4>
    <h6>Gracias por preferirnos</h6>
  </div>
  <div class="modal-footer">
    <input type="button", id="imp-success-btn", class="modal-action modal-close  btn-flat", value="Cerrar">
  </div>
</div><!--modal mensaje final el trigger es el boton enviar del modal 1-->

<!-- MODAL el trigger es el boton impresion -->
<div id="modal4" class="modal">
  <div class="modal-content">
    <button class="close" id="close-modal4"><i class="material-icons">close</i></button>
    <h4>Por favor llene los campos antes de enviar a impresión.</h4>
    <div class="input-field col s12">
      <input type="email", class="validate vk1", placeholder="Email", id="imp_email">
    </div>
    <div class="input-field col s12">
      <input type="text", class="validate vk1", placeholder="Nombre", id="imp_nombre">
    </div>
    <div class="input-field col s12">
      <input type="text", class="validate vk2", placeholder="Rut", id="imp_rut" maxlength="12">
    </div>
  </div>
  <div class="modal-footer">
    <input type="button", id="buttonModal4", class="waves-light btn modal-trigger", value="Enviar", data-form-url="<%= impresion_send_path %>">
  </div>
</div>

<!-- MODAL el trigger de la api del cubidador -->
<div id="modal_cub" class="modal">
  <div class="modal-content col s12 row">
    <button class="close" id="close-modal-cub"><i class="material-icons">close</i></button>
    <h4>Ingrese los m2 para calcular el nº de cajas.</h4>
    <div class="input-field col s5 row">
      <%= form_for(:cubicador, url: cubicador_send_path, html: {id: 'cubicador_form', format: :json}) do |f| %>
        <%= f.hidden_field(:sku, value: nil, id: nil, class: 'cubicador_field') %>
        <%= f.hidden_field(:piso, value: nil, id: nil, class: 'cubicador_field') %>
        <%= f.hidden_field(:superficie, value: nil, id: nil, class: 'cubicador_field') %>
        <i class="material-icons prefix">select_all</i>
        <%= f.number_field(:m2, value: 1, min: 1, class: 'center-align m2_cub cubicador_field vk3', id: nil) %>
        <label for="icon_prefix2">M2</label>
        <%= f.submit("Calcular", class: 'btn input-field') %>
      <% end -%>
    </div>

    <div class="input-field col s2">
      <i class="material-icons prefix">arrow_forward</i>
    </div>

    <div class="input-field col s5">
      Nº de cajas: <span id="num_cajas" data-num-cajas="0">0</span>
      <button class="btn input-field" id="send_carrito_cub" data-carrito-url="<%= carrito_add_path %>" disabled>Enviar al carrito</button>
    </div>
  </div>
</div>

<div class="navbar-fixed "><!--navbar-->
  <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo center">
        <%= image_tag('logo.png') %>
      </a>

      <ul style="float:right">
       <!-- <li>
          <a class=" dropdown-button  btn-flat " id="autorenew_bottom" href="javascript:void(0)">
            <i class="material-icons car carrito-icon">autorenew</i>
          </a>
        </li>-->
      </ul>

      <ul style="float:right">
        <li>
          <a class="dropdown-button btn-flat" href="#!" data-activates="dropdown1" data-delay="50">
            <i class="material-icons car carrito-icon">shopping_basket</i>
            <span class="badge hide" data-count="0" id="carrito-badge" style="display: inline-block;
  float: none !important;
  margin-right: 15px !important;
  margin-left: 15px !important;
  line-height: 22px !important;
  height: 20px !important;
  background-color: white !important;
  color: #E10024 !important;
  border-radius: 14px !important;"></span>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</div>
<div id="loading_app" style="display:none;position:absolute;top:0;bottom:0; z-index:1;background-color:rgba(0, 0, 0, 0.3);width:100%; ">
  <div class="spinner">
    <div class="dot1"></div>
    <div class="dot2"></div>
  </div>

</div>
<div class="fondo" style="display:block;">
<!--  ELIMINE EL SPLASH PRINCIPAL -->
  <div class="main-container" style="/*background-color:red;*/ ">

          <!--  <div id="instrucciones" style="position:absolute;top:10px;bottom:10px; width:80%; padding-right:50px; margin-left:300px; z-index:1;background-color: rgba(0, 0, 0, 0.55);">
                <div style="text-align:center;font-size:3.5em;font-weight:bold;color:#fff;margin-bottom:50px;margin-top:20px;">
                      Vive esta experiencia en 6 pasos.
                </div>

                <div>
                      <ul style="padding-left:40px;color:#fff; font-size:2em;text-align:justify;">
                          <li style="margin-bottom:40px;"><b>Paso #1 : </b>Selecciona Categorías de productos para Pisos y/o Muros en el panel ubicado al costado izquierdo de la pantalla.</li>
                            <li style="margin-bottom:40px;"><b>Paso #2 : </b>Desliza para ver todas los productos de la categoría. </li>
                            <li style="margin-bottom:40px;"><b>Paso #3 :</b> Para Proyectar el producto de tu gusto, debes presionar el botón :
                              <a id="scale-demo"  class="btn-floating btn-small scale-transition set_background">
                                <i class="material-icons">visibility</i>
                              </a> ubicado en la ficha del producto.
                              </li>
                              <li style="margin-bottom:40px;"><b>Paso #4 :</b> Si deseas rotar el producto en la proyección, presiona el botón : <a href="#" class="btn-floating btn-small scale-transition 3d_rotation rotate_background">
                                <i class="material-icons">3d_rotation</i>
                              </a>

                            </a> ubicado en la ficha del producto.</li>
                              <li style="margin-bottom:40px;"><b>Paso #5 :</b> Si deseas incluirlo a tu carro de compras, presiona el botón :  <a class="btn-floating btn-small scale-transition shopping_cart">
                              <i class="material-icons"dropdown-button btn-flat tooltipped>shopping_cart</i>
                            </a> ubicado en la ficha del producto.</li>
                              <li style="margin-bottom:40px;"><b>Paso #6 :</b> Si deseas enviar los productos seleccionados a tu correo, debes pinchar el icono
                                  ubicado en la zona superior izquierda de la pantalla y luego presionar el botón enviar  . Finalmente ingresar tu correo. </li>
                      </ul>
                </div>
            </div>--> 

    <div class="" style="min-height:50%; position:relative;overflow:hidden;">
      <div  style="float:left;width:230px;  position:absolute; top:0; bottom:0; background-color: rgba(0, 0, 0, 0.3); padding-left:10px;">
        <h5 style="margin-top:10px; ">Muros</h5>
        <!-- MUROS -->
        <div class="row" style="margin-bottom:0px;">
          <% categories.each do |cat| %>
            <% if cat.tipo == categories_types[:muro] %>
              <div class="col s6 m6 l6">
                <%= link_to(products_by_category_path(cat.tipo, cat.sodimac_id), class: 'category-link') do %>
                  <%= image_tag(cat.img, class: 'circle hoverable ', alt: cat.alt_txt) %>
                  <span class="title_cat"><%= cat.nombre %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>

      <div style="width:87%;float:right;  padding-left:30px; padding-right:30px;  overflow:hidden;">
        <div  class="slick-carousel" style="margin-left:30px;" id="muros_carousel"></div>
        <br/>
      </div>
    </div>
    <!-- CARRUSEL MUROS-->

    <!-- CARRUSEL PISOS -->
    <div class="" style="width:100%; min-height:50%; position:relative;overflow:hidden;">
      <div  style="width:230px;float:left;position:absolute; top:0; bottom:0; overflow:hidden; background-color: rgba(0, 0, 0, 0.3); padding-left:10px;">
        <h5 style="margin-top:10px;">Pisos</h5>
        <div class="row" style="margin-bottom:0px;">
          <% categories.each do |cat| %>
            <% if cat.tipo == categories_types[:piso] %>
              <div class="col s6 m6 l6">
                <%= link_to(products_by_category_path(cat.tipo, cat.sodimac_id), class: 'category-link') do %>
                  <%= image_tag(cat.img, class: 'circle hoverable ', alt: cat.alt_txt) %>
                  <span class="title_cat"><%= cat.nombre %></span>
                <% end -%>
              </div>
            <% end -%>
          <% end -%>
        </div>
      </div>
      <div style="width:87%;float:right;  height:auto;  padding-left:30px; padding-right:30px; overflow:hidden;position:relative;">
        <div class="slick-carousel" style="margin-left:30px;" id="pisos_carousel"></div>
      </div>
      <!--CARRUSEL PISOS -->
    </div><!--main container -->
</div><!--fondo-->

<footer></footer>

app/views/main/index.html.erb
<div id="loading_app_inicial" style="display:block;z-index:2;position:absolute;top:0;bottom:0;background-color:rgba(0, 0, 0, 0.3);width:100%; ">
  <div class="spinner">
    <div class="dot1"></div>
    <div class="dot2"></div>
  </div>

</div>
<div class="back imgBack" >

  <img id="fondoInicial" src="http://pisosymuros.triplea.cl/images/Fondos/piso-23.jpg" style="display:none;position:absolute;top:0;width: 100vw;
  height: 100vh;
  object-fit: cover;object-fit: cover;z-index:-1;"/>
 <div class="container" style="z-index:1;display:none;" id="content_pantalla_inicio">
    <div class="row">
      <div class="col s12 m12 l12 xl12 center-align">
        <h1 class="flowtext">Te Invitamos a combinar</h1>
        <h2 class="flowtext">Pisos y Muros</h2>
      </div>
    </div>
    <div class="row">
      <div class="col s12 m12 l12 xl12 center-align">
        <%= link_to("Continuar", espacio_path, class: "btn waves-effect waves-ligth")  %>
      </div>
    </div>
  </div>

</div>